/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan_5;

/**
 *
 * @author Ridho
 */
import pertemuan4.MenuUtama;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pertemuan_5.TgsException;

public class KelasemenLigaSawah extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/TugasPBO";
    String user = "postgres";
    String password = "er021105";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelasemenLigaSawah.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public KelasemenLigaSawah() {
        initComponents();
        TampilkanTabel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelKlasemen = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        tfNomor = new javax.swing.JTextField();
        tfKlub = new javax.swing.JTextField();
        tfAsal = new javax.swing.JTextField();
        tfPoint = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        TabelKlasemen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor", "klub", "Asal", "Point"
            }
        ));
        TabelKlasemen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelKlasemenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelKlasemen);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tfNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomorActionPerformed(evt);
            }
        });

        tfPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPointActionPerformed(evt);
            }
        });

        jLabel1.setText("Nomer Daftar");

        jLabel2.setText("Klub");

        jLabel3.setText("Asal Klub");

        jLabel4.setText("Point Kelasemen");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("STSong", 0, 48)); // NOI18N
        jLabel6.setText("KELASEMEN");

        jLabel5.setFont(new java.awt.Font("STSong", 0, 36)); // NOI18N
        jLabel5.setText("LIGA SAWAH");

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInsert)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(Keluar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfKlub, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNomor, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAsal, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnUpdate)
                        .addGap(37, 37, 37)
                        .addComponent(btnDelete)
                        .addGap(41, 41, 41)
                        .addComponent(btnClear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfKlub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void TampilkanTabel() {
        try {
            Class.forName(driver);
            String sql = "SELECT * FROM LigaSawah";
            conn = DriverManager.getConnection(koneksi, user, password);
            stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nomor");
            model.addColumn("Klub");
            model.addColumn("KotaAsal");
            model.addColumn("PointKemenangan");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("Nomor"),
                    rs.getString("Klub"),
                    rs.getString("KotaAsal"),
                    rs.getInt("PointKemenangan")
                });
            }
            this.TabelKlasemen.setModel(model);

            rs.close();
            stmt.close();
            conn.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(KelasemenLigaSawah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (tfNomor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nomor belum diisi");
        } else if (tfKlub.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Klub belum diisi");
        } else if (tfAsal.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kota Asal belum diisi");
        } else if (tfPoint.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Point belum diisi");
        } else {
            try {
                Class.forName(driver);
                String sql = "UPDATE LigaSawah SET PointKemenangan = ?, Klub = ?, KotaAsal = ? WHERE Nomor = ?";
                conn = DriverManager.getConnection(koneksi, user, password);
                pstmt = conn.prepareStatement(sql);

                String Nomor = tfNomor.getText();
                String Klub = tfKlub.getText();
                String Asal = tfAsal.getText();
                String Point = tfPoint.getText();

                
                pstmt.setInt(1, Integer.parseInt(Point)); 
                pstmt.setString(2, Klub);                 
                pstmt.setString(3, Asal);                 
                pstmt.setInt(4, Integer.parseInt(Nomor)); 

                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
                    pstmt.close();
                    conn.close();
                    hilang();
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                try {
                    throw new TgsException("Gagal memperbarui data!");
                } catch (TgsException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
            TampilkanTabel();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tfPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPointActionPerformed

    private void tfNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomorActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:                                        
    hilang();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    String Nomor = tfNomor.getText();

    if (Nomor.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nomor belum diisi untuk menghapus!");
        return;
    }

    try {
        Class.forName(driver);
        conn = DriverManager.getConnection(koneksi, user, password);

        int jawab = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (jawab == JOptionPane.YES_OPTION) {
            String deleteSql = "DELETE FROM LigaSawah WHERE Nomor = ?";
            pstmt = conn.prepareStatement(deleteSql);
            pstmt.setInt(1, Integer.parseInt(Nomor));
            int rowsDeleted = pstmt.executeUpdate();

            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                hilang();
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }

            pstmt.close();
            conn.close();
        } else {
            JOptionPane.showMessageDialog(this, "Data tidak jadi dihapus");
        }
    } catch (ClassNotFoundException | SQLException ex) {
        try {
            throw new TgsException("Gagal menghapus data!");
        } catch (TgsException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    TampilkanTabel();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed

        if (tfNomor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nomor belum diisi");
        } else if (tfKlub.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Klub belum diisi");
        } else if (tfAsal.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kota Asal belum diisi");
        } else if (tfPoint.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Point belum diisi");
        } else {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
                conn.setAutoCommit(false);

                String sql = "INSERT INTO LigaSawah VALUES(?,?,?,?)";
                pstmt = conn.prepareStatement(sql);

                String Nomor = tfNomor.getText();
                String Klub = tfKlub.getText();
                String Asal = tfAsal.getText();
                String Point = tfPoint.getText();

                pstmt.setInt(1, Integer.parseInt(Nomor));
                pstmt.setString(2, Klub);
                pstmt.setString(3, Asal);
                pstmt.setInt(4, Integer.parseInt(Point));

                pstmt.executeUpdate();   
                conn.commit();

                pstmt.close();
                conn.close();

                JOptionPane.showMessageDialog(null, "Sukses diinput");
            } catch (ClassNotFoundException | SQLException ex) {
                try {
                    throw new TgsException("Gagal menyimpan data!");
                } catch (TgsException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
        hilang();
        TampilkanTabel();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
                                      
    int jawab = JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (jawab == JOptionPane.YES_OPTION) {
        System.exit(0); 
    }

    }//GEN-LAST:event_KeluarActionPerformed

    private void TabelKlasemenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelKlasemenMouseClicked
                                           
    int baris = TabelKlasemen.getSelectedRow(); // ambil baris yang diklik
    if (baris != -1) {
        tfNomor.setText(TabelKlasemen.getValueAt(baris, 0).toString());
        tfKlub.setText(TabelKlasemen.getValueAt(baris, 1).toString());
        tfAsal.setText(TabelKlasemen.getValueAt(baris, 2).toString());
        tfPoint.setText(TabelKlasemen.getValueAt(baris, 3).toString());
    }

    }//GEN-LAST:event_TabelKlasemenMouseClicked
    private void hilang() {
        tfNomor.setText("");
        tfKlub.setText("");
        tfAsal.setText("");
        tfPoint.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelasemenLigaSawah().setVisible(true));
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Keluar;
    private javax.swing.JTable TabelKlasemen;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfAsal;
    private javax.swing.JTextField tfKlub;
    private javax.swing.JTextField tfNomor;
    private javax.swing.JTextField tfPoint;
    // End of variables declaration//GEN-END:variables
}
